
destination: ../master
highlighter: pygments
url: "http://simonecnt.github.io"

scholar:
  style: "_bibliography/biblio.csl"
  locale: en
  source: ./_bibliography
  bibliography: biblio.bib
  bibliography_template: "{{ reference }}"
  replace_strings: true
  join_strings: true
  details_dir: bib
  details_layout: bib_detail.html
  details_link: " Details"
  query: "@*"
  bibliography_list_tag: ul

sass:
    sass_dir: _sass
    style: compressed

