
destination: ../master
permalink: pretty
url: "https://3dz2.com"

scholar:
  style: "_bibliography/biblio.csl"
  locale: en
  source: ./_bibliography
  bibliography: biblio.bib
  bibliography_template: "{{ reference }}"
  replace_strings: true
  join_strings: true
  details_dir: publications
  details_layout: bib_detail.html
  details_link: " Details"
  query: "@*"
  bibliography_list_tag: ul

sass:
    style: compressed
    sourcemap: never

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

